from __future__ import annotations

from enum import Enum


class VectorTable(str, Enum):
    IMAGE_INTELLIGENCE_ADA = "IMAGE_INTELLIGENCE_ADA"
    IMAGE_INTELLIGENCE_MINI_LM = "IMAGE_INTELLIGENCE_MINI_LM"
    NARRATIVE_ADA = "NARRATIVE_ADA"
    VIDEO_DNA = "VIDEO_DNA"
    VIDEO_DNA_FULL = "VIDEO_DNA_FULL"
    REVIEWER_FEEDBACK = "REVIEWER_FEEDBACK"
